<?php

namespace DreamFactory\Core\AMQP\Resources;

class Sub extends \DreamFactory\Core\PubSub\Resources\Sub
{
    protected function handlePOST()
    {
        return parent::handlePOST(); // TODO: Change the autogenerated stub
    }
}