<?php

namespace DreamFactory\Core\AMQP\Resources;

use DreamFactory\Core\Resources\BaseRestResource;

class Sub extends BaseRestResource
{
    const RESOURCE_NAME = 'sub';

    protected function handlePOST()
    {
        return parent::handlePOST(); // TODO: Change the autogenerated stub
    }
}